export const BASE_PRICES = {
  "OG Kush": 30,
  "Sour Diesel": 35,
  "Green Crack": 40,
  "Grandaddy Purple": 45,
  "Poor Quality Meth": 60,
  Meth: 80,
  "High-Quality Meth": 110,
  Cocaine: 150,
} as const;

export const EFFECT_MULTIPLIERS = {
  "Anti-Gravity": 0.54,
  Athletic: 0.32,
  Balding: 0.3,
  "Bright-Eyed": 0.4,
  Calming: 0.1,
  "Calorie-Dense": 0.28,
  Cyclopean: 0.56,
  Disorienting: 0.0,
  Electrifying: 0.5,
  Energizing: 0.22,
  Euphoric: 0.18,
  Explosive: 0.0,
  Focused: 0.16,
  Foggy: 0.36,
  Gingeritis: 0.2,
  Glowing: 0.48,
  Jennerising: 0.42,
  Laxative: 0.0,
  "Long Faced": 0.52,
  Munchies: 0.12,
  Paranoia: 0.0,
  Refreshing: 0.14,
  Schizophrenia: 0.0,
  Sedating: 0.26,
  "Seizure-Inducing": 0.0,
  Shrinking: 0.6,
  Slippery: 0.34,
  Smelly: 0.0,
  Sneaky: 0.24,
  Spicy: 0.38,
  "Thought-Provoking": 0.44,
  Toxic: 0.0,
  "Tropic Thunder": 0.46,
  Zombifying: 0.58,
} as const;

export const INGREDIENT_PRICES = {
  Cuke: 2,
  Banana: 2,
  Paracetamol: 3,
  Donut: 3,
  Viagra: 4,
  "Mouth Wash": 4,
  "Flu Medicine": 5,
  Gasoline: 5,
  "Energy Drink": 6,
  "Motor Oil": 6,
  "Mega Bean": 7,
  Chili: 7,
  Battery: 8,
  Iodine: 8,
  Addy: 9,
  "Horse Semen": 9,
} as const;

export const ITEMS_DATA = {
  Cuke: {
    baseEffect: "Energizing",
    replacements: [
      ["Euphoric", "Laxative"],
      ["Foggy", "Cyclopean"],
      ["Gingeritis", "Thought-Provoking"],
      ["Munchies", "Athletic"],
      ["Slippery", "Munchies"],
      ["Sneaky", "Paranoia"],
      ["Toxic", "Euphoric"],
    ],
  },
  "Flu Medicine": {
    baseEffect: "Sedating",
    replacements: [
      ["Athletic", "Munchies"],
      ["Calming", "Bright-Eyed"],
      ["Cyclopean", "Foggy"],
      ["Electrifying", "Refreshing"],
      ["Euphoric", "Toxic"],
      ["Focused", "Calming"],
      ["Laxative", "Euphoric"],
      ["Munchies", "Slippery"],
      ["Shrinking", "Paranoia"],
      ["Thought-Provoking", "Gingeritis"],
    ],
  },
  Gasoline: {
    baseEffect: "Toxic",
    replacements: [
      ["Disorienting", "Glowing"],
      ["Electrifying", "Disorienting"],
      ["Energizing", "Euphoric"],
      ["Euphoric", "Spicy"],
      ["Gingeritis", "Smelly"],
      ["Jennerising", "Sneaky"],
      ["Laxative", "Foggy"],
      ["Munchies", "Sedating"],
      ["Paranoia", "Calming"],
      ["Shrinking", "Focused"],
      ["Sneaky", "Tropic Thunder"],
    ],
  },
  Donut: {
    baseEffect: "Calorie-Dense",
    replacements: [
      ["Anti-Gravity", "Slippery"],
      ["Balding", "Sneaky"],
      ["Calorie-Dense", "Explosive"],
      ["Focused", "Euphoric"],
      ["Jennerising", "Gingeritis"],
      ["Munchies", "Calming"],
      ["Shrinking", "Energizing"],
    ],
  },
  "Energy Drink": {
    baseEffect: "Athletic",
    replacements: [
      ["Disorienting", "Electrifying"],
      ["Euphoric", "Energizing"],
      ["Focused", "Shrinking"],
      ["Foggy", "Laxative"],
      ["Glowing", "Disorienting"],
      ["Schizophrenia", "Balding"],
      ["Sedating", "Munchies"],
      ["Spicy", "Euphoric"],
      ["Tropic Thunder", "Sneaky"],
    ],
  },
  "Mouth Wash": {
    baseEffect: "Balding",
    replacements: [
      ["Calming", "Anti-Gravity"],
      ["Calorie-Dense", "Sneaky"],
      ["Explosive", "Sedating"],
      ["Focused", "Jennerising"],
    ],
  },
  "Motor Oil": {
    baseEffect: "Slippery",
    replacements: [
      ["Energizing", "Munchies"],
      ["Euphoric", "Sedating"],
      ["Foggy", "Toxic"],
      ["Munchies", "Schizophrenia"],
      ["Paranoia", "Anti-Gravity"],
    ],
  },
  Banana: {
    baseEffect: "Gingeritis",
    replacements: [
      ["Calming", "Sneaky"],
      ["Cyclopean", "Energizing"],
      ["Disorienting", "Focused"],
      ["Energizing", "Thought-Provoking"],
      ["Focused", "Seizure-Inducing"],
      ["Long Faced", "Refreshing"],
      ["Paranoia", "Jennerising"],
      ["Smelly", "Anti-Gravity"],
      ["Toxic", "Smelly"],
    ],
  },
  Chili: {
    baseEffect: "Spicy",
    replacements: [
      ["Anti-Gravity", "Tropic Thunder"],
      ["Athletic", "Euphoric"],
      ["Laxative", "Long Faced"],
      ["Munchies", "Toxic"],
      ["Shrinking", "Refreshing"],
      ["Sneaky", "Bright-Eyed"],
    ],
  },
  Iodine: {
    baseEffect: "Jennerising",
    replacements: [
      ["Calming", "Balding"],
      ["Calorie-Dense", "Gingeritis"],
      ["Euphoric", "Seizure-Inducing"],
      ["Foggy", "Paranoia"],
      ["Refreshing", "Thought-Provoking"],
      ["Toxic", "Sneaky"],
    ],
  },
  Paracetamol: {
    baseEffect: "Sneaky",
    replacements: [
      ["Calming", "Slippery"],
      ["Electrifying", "Athletic"],
      ["Energizing", "Paranoia"],
      ["Focused", "Gingeritis"],
      ["Foggy", "Calming"],
      ["Glowing", "Toxic"],
      ["Munchies", "Anti-Gravity"],
      ["Paranoia", "Balding"],
      ["Spicy", "Bright-Eyed"],
      ["Toxic", "Tropic Thunder"],
    ],
  },
  Viagra: {
    baseEffect: "Tropic Thunder",
    replacements: [
      ["Athletic", "Sneaky"],
      ["Disorienting", "Toxic"],
      ["Euphoric", "Bright-Eyed"],
      ["Laxative", "Calming"],
      ["Shrinking", "Gingeritis"],
    ],
  },
  "Horse Semen": {
    baseEffect: "Long Faced",
    replacements: [
      ["Anti-Gravity", "Calming"],
      ["Gingeritis", "Refreshing"],
      ["Seizure-Inducing", "Energizing"],
      ["Thought-Provoking", "Electrifying"],
    ],
  },
  "Mega Bean": {
    baseEffect: "Foggy",
    replacements: [
      ["Athletic", "Laxative"],
      ["Calming", "Glowing"],
      ["Energizing", "Cyclopean"],
      ["Focused", "Disorienting"],
      ["Jennerising", "Paranoia"],
      ["Seizure-Inducing", "Focused"],
      ["Shrinking", "Electrifying"],
      ["Slippery", "Toxic"],
      ["Sneaky", "Calming"],
      ["Thought-Provoking", "Energizing"],
    ],
  },
  Addy: {
    baseEffect: "Thought-Provoking",
    replacements: [
      ["Explosive", "Euphoric"],
      ["Foggy", "Energizing"],
      ["Glowing", "Refreshing"],
      ["Long Faced", "Electrifying"],
      ["Sedating", "Gingeritis"],
    ],
  },
  Battery: {
    baseEffect: "Bright-Eyed",
    replacements: [
      ["Cyclopean", "Glowing"],
      ["Electrifying", "Euphoric"],
      ["Euphoric", "Zombifying"],
      ["Laxative", "Calorie-Dense"],
      ["Munchies", "Tropic Thunder"],
      ["Shrinking", "Munchies"],
    ],
  },
} as const;

export type Effect = keyof typeof EFFECT_MULTIPLIERS;
export type BaseProduct = keyof typeof BASE_PRICES;
export type Ingredient = keyof typeof INGREDIENT_PRICES;
export type ItemData = typeof ITEMS_DATA;

export const ALL_EFFECTS = Object.keys(EFFECT_MULTIPLIERS) as Effect[];
